version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:5.2.1
    hostname: kafka
    container_name: kafka
    ports:
      - '9092:9092'
      - '29092:29092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ## for local use
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      ## for public use
      #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://35.236.145.238:9092
      #advertised.host.name: 35.236.145.238
  
  # restproxy:
  #   image: confluentinc/cp-kafka-rest:5.2.1
  #   restart: always
  #   container_name: restproxy
  #   hostname: restproxy
  #   depends_on:
  #     - kafka
  #   environment:
  #     KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_REST_LISTENERS: http://0.0.0.0:8082
  #     KAFKA_REST_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
  #     KAFKA_REST_HOST_NAME: restproxy
  #     KAFKA_REST_DEBUG: "true"
  #   ports:
  #     - 8082:8082

  # ksql-server:
  #   image: confluentinc/cp-ksql-server:5.2.1
  #   container_name: ksql-server
  #   depends_on:
  #     - kafka
  #   ports:
  #     - "8088:8088"
  #   environment:
  #     KSQL_CONFIG_DIR: "/etc/ksql"
  #     KSQL_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/ksql/log4j-rolling.properties"
  #     KSQL_BOOTSTRAP_SERVERS: kafka:9092
  #     KSQL_LISTENERS: "http://0.0.0.0:8088"
  #     KSQL_CACHE_MAX_BYTES_BUFFERING: 0
  #     KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"

  # ksql-cli:
  #   image: confluentinc/cp-ksql-cli:5.2.1
  #   container_name: ksql-cli
  #   depends_on:
  #     - kafka
  #     - ksql-server
  #   entrypoint: /bin/sh
  #   tty: true

