version: '2'
services:

  jupyter-keras:
    image: gaarv/jupyter-keras
    container_name: jupyter-keras
    hostname: jupyter-keras
    ports:
      - "8887:8888"
    command: start-notebook.sh --NotebookApp.token=''
    volumes:
      - ./jupyter-keras:/home/jovyan/Project
    restart: always
