FROM python:3.7
MAINTAINER BenLiu
# add project
#ADD ./formal_code /app

WORKDIR /app

# install flask
RUN pip install --upgrade pip
RUN pip install Flask==1.0.2


##run flask
##Developer use
#CMD ["python"]

#Production use
#CMD ["python", "app.py"]
